urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jesse.views.home', name='home'),
    # url(r'^jesse/', include('jesse.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )


if settings.DEBUG:
    urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
    ) 

gallery/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Gallery(models.Model):
    name = models.CharField(max_length=255)
    #description = models.TextField(max_length=10000, help_text="This text appears on the portfolio overview page.")
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return reverse('gallery_view', args=[self.pk])
    class Meta:
        verbose_name_plural = 'galleries'
    
class Image(models.Model):
    gallery = models.ForeignKey(Gallery)
    order = models.IntegerField()
    image = models.ImageField(upload_to="uploads/galleryImages/")
    title = models.TextField(max_length=1255, blank=True)
    caption = models.TextField(max_length=10000, blank=True)
    
    class Meta:
        ordering = ["order"]
    
    def __unicode__(self):
        return str(self.order)

#stuff you need to make it a plugin
from cms.models import CMSPlugin

class GalleryPlugin(CMSPlugin):
    gallery = models.ForeignKey('gallery.Gallery', related_name='plugins')
    #page = models.CharField(max_length=255)
    def __unicode__(self):
        return self.gallery.name

random_background/models.py
from django.db import models

class BackgroundImageSet(models.Model):
    name = models.CharField(max_length=255)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'background image sets'

class BackgroundImage(models.Model):
    imageset = models.ForeignKey(BackgroundImageSet)
    image = models.ImageField(upload_to="uploads/backgroundImages/")
    #def __unicode__(self):
        #return self.image

from cms.models import CMSPlugin

class BackgroundImagePlugin(CMSPlugin):
    backgroundimage = models.ForeignKey('random_background.BackgroundImageSet',related_name='plugins')
    def __unicode__(self):
        return self.backgroundimage.name

random_background/views.py
# Create your views here.

templates/about.html
{% extends "base.html" %}
{% load cms_tags %}


{% block body_class %}about{% endblock %}
{% block topnav %}
    <li>{% show_placeholder "cv" "topmatter"%}</li>
    <li>{% show_placeholder "twitter" "topmatter"%}</li>
    <li>{% show_placeholder "about" "topmatter"%}</li>
    <li>{% show_placeholder "contact" "topmatter"%}</li>
{% endblock %}

{% block base_content %}
    <div id="content">
	<div id="top-content">
	    <div class="top-content-inner">
		<h2 class="pageHeading">About</h2>
		{% placeholder about_content %}
	    </div>
	</div>
    </div>
{% endblock %}
{% block foot_contact %}
    {% show_placeholder "contact" "footermatter"%}
{% endblock %}
{% block random_bg %}
{% placeholder random_background %}
{% endblock %}

templates/base.html
{% load cms_tags sekizai_tags menu_tags %}
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    {% render_block "css" %}
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
    <link href='http://fonts.googleapis.com/css?family=Enriqueta:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{{STATIC_URL}}css/style.css">

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <script src="{{STATIC_URL}}js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body class="{% block body_class %}{% endblock %}">
    {% cms_toolbar %}
    <div id="container">
        <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
             chromium.org/developers/how-tos/chrome-frame-getting-started -->
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
        <header>
            <h1 class="logo"><a href="/"><span>Jesse</span> <span class="ryan">Ryan</span> <span>Kuroiwa</span></a></h1>
          <ul id="nav">
              {% show_menu 0 100 0 100 %}
          </ul>
        </header>
        <div id="main" role="main">
            <div id="top-container">
                <ul id="topnav">
		{% block topnav %}{% endblock %}
                </ul>
            </div>
          <div id="main-content">
            {% block base_content %}{% endblock %}
            <footer>
                <p class="copyright">&copy; {% now "Y"%} Jesse Kuroiwa | {% block foot_contact %}{% endblock %} | <a href="/about/">About</a> | Boulder Colorado</p>
            </footer>
          </div>
        </div>

    </div>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{STATIC_URL}}js/libs/jquery-1.7.1.min.js"><\/script>')</script>
    {% block random_bg %}{% endblock %} 
  <!-- scripts concatenated and minified via build script -->
  <script src="{{STATIC_URL}}js/plugins.js"></script>
  <script src="{{STATIC_URL}}js/script.js"></script>
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <!--script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script-->
  {% render_block "js" %}
</body>
</html>

templates/cms/plugins/teaser.html
{% load i18n %}
<div class="teaser">
    <h2>{{ object.title|title }}</h2>
    {% if object.image %}
            {% if link %}<a href="{{ link }}">{% endif %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}"/>
            {% if link %}</a>{% endif %}
    {% endif %}
    {% if object.description %}
    <p>{{ object.description|linebreaksbr }}</p>
    {% endif %}
    {% if link %}<a class="more" href="{{ link }}">{% trans "more" %} &#187;</a>{% endif %}
</div>

templates/footermatter.html
{% load cms_tags sekizai_tags menu_tags %}
{% render_block "css" %}
{% placeholder contact %}
{% render_block "js" %}

templates/gallery-overview.html
{% load thumbnail %}
{% load cms_tags %}
<div class="gallery-wrapper">
    <h2>{{ gallery.name }}</h2>
    {% for image in gallery.image_set.all %}
    {% if forloop.first %}
    <p><img src="{% thumbnail image.image 376x0 %}" alt="{{ image.title }}"></p>
    {% endif %}
    {% endfor %}
    <p>{{ gallery.description }}</p>
    <p>URL: {{ gallery.get_absolute_url }}</p>
</div>

templates/gallery.html
{% load thumbnail %}
<div class="gallery-wrapper">
    <h2>{{ gallery.name }}<span class="counter"><span class="number"></span>/<span class="max"></span></span></h2>
    
    <div id="{{ gallery.name|lower }}" class="gallery">
	    
	    <ul class="images">
		{% for image in gallery.image_set.all %}
		<li class="image">
		    <div class="image-background">
			<a href="#prev" class="prev"></a>
			<div class="imgControl" data-fullsize="{{MEDIA_URL}}{{image.image}}">
			    <div class="fullScreen"></div>
			    <img src="{% thumbnail image.image 376x0 %}" alt="{{ image.title }}">
			</div>
			<a href="#next" class="next"></a>
		    </div>
		    <div class="imageText">
			<h2>{{ image.title|linebreaksbr }}</h2>
			<p>{{ image.caption|linebreaksbr }}</p>
		    </div>
		</li>
		{% endfor %}
	    </ul>
	<a href="#next" class="thumb-next"></a>    
	<div class="thumb-container">
	    
	    <ul class="thumbs">
		{% for image in gallery.image_set.all %}
		<li class="thumb">
		    <img class="thumbnail" src="{% thumbnail image.image 42x42 crop %}" alt="{{ image.title }}" title="{{ image.title }}"/>
		</li>
		{% endfor %}
	    </ul>
	    
	</div>
	<a href="#prev" class="thumb-prev"></a>
    </div>
</div>

templates/home.html
{% extends "base.html" %}
{% load cms_tags %}
{% block body_class %}home{% endblock %}
{% block topnav %}
    <li>{% show_placeholder "cv" "topmatter"%}</li>
    <li>{% show_placeholder "twitter" "topmatter"%}</li>
    <li>{% show_placeholder "about" "topmatter"%}</li>
    <li>{% show_placeholder "contact" "topmatter"%}</li>
{% endblock %}
{% block base_content %}
    <div id="content">
	<div id="top-content">
	    <div class="top-content-inner">
		{% placeholder about_teaser %}
	    </div>
	</div>
	<h2 class="category-heading">News</h2>
	<div id="bottom-content">
	    <div class="bottom-content-inner">
		{% placeholder news_teasers %}
	    </div>
	</div>
    </div>
{% endblock %}
{% block foot_contact %}
    {% show_placeholder "contact" "footermatter"%}
{% endblock %}
{% block random_bg %}
{% placeholder random_background %}
{% endblock %}

templates/index.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <link rel="stylesheet" href="css/style.css">

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <script src="js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>

  </header>
  <div role="main">

  </div>
  <footer>

  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <!-- scripts concatenated and minified via build script -->
  <script src="js/plugins.js"></script>
  <script src="js/script.js"></script>
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>

templates/links.html
{% extends "base.html" %}
{% load cms_tags %}
{% block body_class %}links{% endblock %}
{% block topnav %}
    <li>{% show_placeholder "cv" "topmatter"%}</li>
    <li>{% show_placeholder "twitter" "topmatter"%}</li>
    <li>{% show_placeholder "about" "topmatter"%}</li>
    <li>{% show_placeholder "contact" "topmatter"%}</li>
{% endblock %}
{% block base_content %}
    <div id="content">
	<div id="top-content">
	    <div class="top-content-inner">
                <h2 class="pageHeading">Links</h2>
		{% placeholder links_content %}
	    </div>
	</div>
    </div>
{% endblock %}
{% block foot_contact %}
    {% show_placeholder "contact" "footermatter"%}
{% endblock %}
{% block random_bg %}
  {% placeholder random_background %}
{% endblock %}

templates/news.html
{% extends "base.html" %}
{% load cms_tags %}
{% block body_class %}news{% endblock %}
{% block topnav %}
    <li>{% show_placeholder "cv" "topmatter"%}</li>
    <li>{% show_placeholder "twitter" "topmatter"%}</li>
    <li>{% show_placeholder "about" "topmatter"%}</li>
    <li>{% show_placeholder "contact" "topmatter"%}</li>
{% endblock %}
{% block base_content %}
    <div id="content">
	<div id="top-content">
	    <div class="top-content-inner">
                <h2 class="pageHeading">News</h2>
		{% placeholder news_content %}
	    </div>
	</div>
    </div>
{% endblock %}
{% block foot_contact %}
    {% show_placeholder "contact" "footermatter"%}
{% endblock %}
{% block random_bg %}
{% placeholder random_background %}
{% endblock %}

templates/portfolio.html
{% extends "base.html" %}
{% load cms_tags %}
{% block body_class %}portfolio-overview{% endblock %}
{% block topnav %}
    <li>{% show_placeholder "cv" "topmatter"%}</li>
    <li>{% show_placeholder "twitter" "topmatter"%}</li>
    <li>{% show_placeholder "about" "topmatter"%}</li>
    <li>{% show_placeholder "contact" "topmatter"%}</li>
{% endblock %}
{% block base_content %}
    <div id="content">
	{% placeholder gallery %}
    </div>
{% endblock %}
{% block foot_contact %}
    {% show_placeholder "contact" "footermatter"%}
{% endblock %}

templates/random-bg.html
<script>
  var images = [{%for image in backgroundimage.backgroundimage_set.all%}"{{MEDIA_URL}}{{image.image}}"{%if not forloop.last%},{%endif%}{%endfor%}];
</script>

templates/topmatter.html
{% load cms_tags sekizai_tags menu_tags %}
{% render_block "css" %}
<li>{% placeholder cv %}</li>
<li>{% placeholder twitter %}</li>
<li>{% placeholder about %}</li>
<li>{% placeholder contact %}</li>
{% render_block "js" %}